name: StaticScanVeraCode

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  veracode-static-scan:
    runs-on: ubuntu-latest
    environment: staticscan
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Install Node tools
        run: npm install -g vsce webpack webpack-cli

      - name: Build VSIX (linux-x64)
        run: dotnet cake --target=vsix --configuration=release --arch=linux-x64

      - name: Zip entire project for Veracode
        run: 7z a veracode-auto-pack-DotRush-dotnet-js.zip . '-xr!.git' '-xr!artifacts'

      - name: Get timestamp
        run: echo TIMESTAMP=$(date +%Y-%m-%d_%H:%M:%S) >> $GITHUB_ENV

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: DotRush
          createprofile: false
          filepath: veracode-auto-pack-DotRush-dotnet-js.zip
          version: ${{env.TIMESTAMP}}
          vid: ${{ secrets.VERACODE_API_KEY_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY_SECRET }}
          deleteincompletescan: 1

